Microsoft Windows [Version 10.0.19045.6216]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\Виктор\PycharmProjects\PythonProject2>.venv\Scripts\activate     

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>pip install cowsay
Collecting cowsay
  Downloading cowsay-6.1-py3-none-any.whl.metadata (5.6 kB)
Downloading cowsay-6.1-py3-none-any.whl (25 kB)
Installing collected packages: cowsay
Successfully installed cowsay-6.1

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>pip list
Package          Version
---------------- -------
cowsay           6.1
OpenOPC-Python3x 1.3.1
pip              25.1.1
Pyro4            4.82
serpent          1.41

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>deactivate
C:\Users\Виктор\PycharmProjects\PythonProject2>pip list
Package          Version
---------------- -------
asgiref          3.9.1
Django           5.2.5
OpenOPC-Python3x 1.3.1
pip              25.2
Pyro4            4.82
serpent          1.41
sqlparse         0.5.3
tzdata           2025.2

C:\Users\Виктор\PycharmProjects\PythonProject2>.venv\Scripts\activate

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t 234
  ___
| 234 |
  ===
   \
    \
      ^__^
      (oo)\_______
      (__)\       )\/\
          ||----w |
          ||     ||

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>deactivate             
C:\Users\Виктор\PycharmProjects\PythonProject2>.venv\Scripts\activate 

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t Hello world im cow Lucy
usage: Cowsay [-h] [-c CHARACTER] -t TEXT [-v]
Cowsay: error: unrecognized arguments: world im cow Lucy

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t Hello world            
usage: Cowsay [-h] [-c CHARACTER] -t TEXT [-v]
Cowsay: error: unrecognized arguments: world

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t Hello      
  _____
| Hello |
  =====
     \
      \
        ^__^
        (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t Hello_world
  ___________
| Hello_world |
  ===========
           \
            \
              ^__^
              (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t Hello_world_im_cow_Lucy
  _______________________
| Hello_world_im_cow_Lucy |
  =======================
                       \
                        \
                          ^__^
                          (oo)\_______
                          (__)\       )\/\
                              ||----w |
                              ||     ||

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>deactivate                        
C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t 234          
"cowsay" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

C:\Users\Виктор\PycharmProjects\PythonProject2>.venv\Scripts\activate 

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>cowsay -t 234          
  ___
| 234 |
  ===
   \
    \
      ^__^
      (oo)\_______
      (__)\       )\/\
          ||----w |
          ||     ||

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>python3 -m venv ll_env
Python 
(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>diactivate
"diactivate" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(.venv) C:\Users\Виктор\PycharmProjects\PythonProject2>deactivate  
C:\Users\Виктор\PycharmProjects\PythonProject2> -m venv ll_env
"-m" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

C:\Users\Виктор\PycharmProjects\PythonProject2>mkdir learning_log

C:\Users\Виктор\PycharmProjects\PythonProject2>cd learning_log

C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python -m venv ll_env

C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>source ll_env/bin/activate
"source" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ll_env\Scripts\activate 

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>pip install django
Collecting django
  Using cached django-5.2.5-py3-none-any.whl.metadata (4.1 kB)
Collecting asgiref>=3.8.1 (from django)
  Using cached asgiref-3.9.1-py3-none-any.whl.metadata (9.3 kB)
Collecting sqlparse>=0.3.1 (from django)
Collecting tzdata (from django)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached django-5.2.5-py3-none-any.whl (8.3 MB)
Using cached asgiref-3.9.1-py3-none-any.whl (23 kB)
Using cached sqlparse-0.5.3-py3-none-any.whl (44 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, sqlparse, asgiref, django
Successfully installed asgiref-3.9.1 django-5.2.5 sqlparse-0.5.3 tzdata-2025.2

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log .    

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls learning_log
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log.ls
CommandError: 'learning_log.ls' is not a valid project name. Please make sure the name is a valid identifier.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log   
CommandError: 'C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log' already exists

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log . 
CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls learning_log django-admin startproject learning_log .
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls learning_log django-admin startproject learning_log .
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log .
CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log .
CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls learning_log django-admin startproject learning_log .
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log       

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27    <DIR>          learning_log
02.09.2025  10:13    <DIR>          ll_env
02.09.2025  10:27               690 manage.py
               1 файлов            690 байт
               4 папок  401 531 822 080 байт свободно

CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>manage.py

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log .        
CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log .        
CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27    <DIR>          learning_log
02.09.2025  10:13    <DIR>          ll_env
02.09.2025  10:27               690 manage.py
               1 файлов            690 байт
               4 папок  401 296 326 656 байт свободно

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>django-admin startproject learning_log . 
CommandError: C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>cd learning_log

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27               417 asgi.py
02.09.2025  10:27             3 301 settings.py
02.09.2025  10:27               790 urls.py
02.09.2025  10:27               417 wsgi.py
02.09.2025  10:27                 0 __init__.py
               5 файлов          4 925 байт
               2 папок  401 295 757 312 байт свободно

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>cd ..

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27    <DIR>          learning_log
02.09.2025  10:13    <DIR>          ll_env
02.09.2025  10:27               690 manage.py
               1 файлов            690 байт
               4 папок  401 295 470 592 байт свободно
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>cd learning_log
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D
 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log
02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27               417 asgi.py
02.09.2025  10:27             3 301 settings.py
02.09.2025  10:27               790 urls.py
02.09.2025  10:27               417 wsgi.py
02.09.2025  10:27                 0 __init__.py
               5 файлов          4 925 байт
               2 папок  401 295 536 128 байт свободно
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>python manage.py migrate
python: can't open file 'C:\\Users\\Виктор\\PycharmProjects\\PythonProject2\\learning_log\\learning_log\\manage.py': [Errno 2] No such file or directory

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27               417 asgi.py
02.09.2025  10:27             3 301 settings.py
02.09.2025  10:27               790 urls.py
02.09.2025  10:27               417 wsgi.py
02.09.2025  10:27                 0 __init__.py
               5 файлов          4 925 байт
               2 папок  401 293 217 792 байт свободно

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>python manage.py migrate
python: can't open file 'C:\\Users\\Виктор\\PycharmProjects\\PythonProject2\\learning_log\\learning_log\\manage.py': [Errno 2] No such file or directory

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27               417 asgi.py
02.09.2025  10:27             3 301 settings.py
02.09.2025  10:27               790 urls.py
02.09.2025  10:27               417 wsgi.py
02.09.2025  10:27                 0 __init__.py
               5 файлов          4 925 байт
               2 папок  401 292 959 744 байт свободно

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>cd learning log
Системе не удается найти указанный путь.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>cd learning_log
Системе не удается найти указанный путь.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>python manage.py migrate
python: can't open file 'C:\\Users\\Виктор\\PycharmProjects\\PythonProject2\\learning_log\\learning_log\\manage.py': [Errno 2] No such file or directory

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>cd manage.py
Системе не удается найти указанный путь.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log

02.09.2025  10:27    <DIR>          .
02.09.2025  10:27    <DIR>          ..
02.09.2025  10:27               417 asgi.py
02.09.2025  10:27             3 301 settings.py
02.09.2025  10:27               790 urls.py
02.09.2025  10:27               417 wsgi.py
02.09.2025  10:27                 0 __init__.py
               5 файлов          4 925 байт
               2 папок  401 292 345 344 байт свободно

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>New-Item manage.py
"New-Item" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\learning_log>cd C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>New-Item manage.py
"New-Item" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>ls
"ls" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>dir
 Том в устройстве C не имеет метки.
 Серийный номер тома: 9250-BF9D

 Содержимое папки C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log

02.09.2025  11:06    <DIR>          .
02.09.2025  11:06    <DIR>          ..
02.09.2025  11:06           131 072 db.sqlite3
02.09.2025  11:06    <DIR>          learning_log
02.09.2025  10:13    <DIR>          ll_env
02.09.2025  10:27               690 manage.py
               2 файлов        131 762 байт
               4 папок  401 290 145 792 байт свободно

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>manage.py

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 02, 2025 - 11:10:05
Django version 5.2.5, using settings 'learning_log.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>F\EF\
"F\EF\" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>EF
"EF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>E
"E" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>F
"F" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>\F\FE
Системе не удается найти указанный путь.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>W
"W" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>EF
"EF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WE
"WE" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>FWE
"FWE" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>F
"F" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEF
"WEF" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>WEADWAWDADAWDAWD
"WEADWAWDADAWDAWD" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>A

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>AWD
"AWD" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>AWDADWAWDAWDAWDA
"AWDADWAWDAWDAWDA" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

"WD" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>AWD
"AWD" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 02, 2025 - 11:58:42
Django version 5.2.5, using settings 'learning_log.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
[02/Sep/2025 12:07:57] "GET / HTTP/1.1" 200 12068
[02/Sep/2025 12:07:58] "GET / HTTP/1.1" 200 12068


Добавление файла 0001_initial.py:

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py makemigrations learning_logs
Traceback (most recent call last):
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Виктор\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\contrib\admin\models.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\contrib\contenttypes\models.py", line 134, in <module>
    class ContentType(models.Model):
    ...<53 lines>...
            return (self.app_label, self.model)
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\db\models\base.py", line 136, in __new__
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py makemigrations learning_logs
Traceback (most recent call last):
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log\ll_env\Lib\site-packages\django\apps\registry.py", line 93, in populate
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: admin

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py makemigrations learning_logs
Migrations for 'learning_logs':
  learning_logs\migrations\0001_initial.py
    + Create model Topic

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>

SQL:

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py makemigrations learning_logs
Migrations for 'learning_logs':
  learning_logs\migrations\0001_initial.py
    + Create model Topic

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.p
y sqlmigrate learning_logs 0001
BEGIN;
--
-- Create model Topic
--
CREATE TABLE "learning_logs_topic" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" varchar(200) NOT NULL, "date_added" datetime NOT NULL);
COMMIT;

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py sqlmigrate learning_logs 0001 BEGIN;
usage: manage.py sqlmigrate [-h] [--database {default}] [--backwards] [--version]
                            [-v {0,1,2,3}] [--settings SETTINGS]
                            [--pythonpath PYTHONPATH] [--traceback] [--no-color]    
                            [--force-color] [--skip-checks]
                            app_label migration_name
manage.py sqlmigrate: error: unrecognized arguments: BEGIN;

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, learning_logs, sessions
Running migrations:
  Applying learning_logs.0001_initial... OK

(ll_env) C:\Users\Виктор\PycharmProjects\PythonProject2\learning_log>
